version: "3.7"
services:
  gateway:
    build: ./gateway
    restart: 'always'
    ports:
      - "3000:3000"
    depends_on:
      - td_api
  td_ingest:
    build: ./services/td/td_ingest
    restart: 'on-failure'
    environment:
      broker__host: broker
      broker__username: ${RAILDATA_BROKER_USER}
      broker__password: ${RAILDATA_BROKER_PASSWORD}
      td_redis__host: td_db
    depends_on:
      - broker
  td_api:
    build: ./services/td/td_api
    restart: 'on-failure'
    environment:
      td_redis__host: td_db
    depends_on: 
      - td_db
    ports:
      - "3000"
  td_db:
    image: redis
  stomp-bridge:
    build: ./services/stomp-bridge
    restart: 'on-failure'
    environment:
      broker__host: broker
      broker__username: ${RAILDATA_BROKER_USER}
      broker__password: ${RAILDATA_BROKER_PASSWORD}
      feeds__networkrail__username: ${NETWORKRAIL_USER}
      feeds__networkrail__password: ${NETWORKRAIL_PASSWORD}
      feeds__networkrail__durablity: ${NETWORKRAIL_DURABLE}
      feeds__networkrail__system_name: ${RAILDATA_SYSTEMNAME}
    depends_on:
      - broker
  broker:
    hostname: "broker"
    build: ./broker/
    ports:
      - "15672:15672"
      - "5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RAILDATA_BROKER_USER}
      RABBITMQ_DEFAULT_PASS: ${RAILDATA_BROKER_PASSWORD}